# Generated by Django 5.2.17 on 2026-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(help_text='ISO 4217', max_length=3)),
                ('regulator_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Shown in country pickers')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
