# Generated by Django 5.2.17 on 2026-09-30 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('message', models.CharField(max_length=500)),
                ('stack', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, help_text='Page path without query string', max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('release', models.CharField(blank=True, max_length=60)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
