# Generated by Django 5.2.17 on 2026-09-30 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('answered', 'Answered from reviewed records'), ('no_reviewed_data', 'No reviewed records matched'), ('unverified', 'Answer failed verification (not shown)'), ('unavailable', 'Assistant not configured'), ('error', 'Model call failed')], max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('retrieved', models.JSONField(blank=True, default=list, help_text='Generic slugs given as context')),
                ('model', models.CharField(blank=True, max_length=60)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
