# Generated by Django 5.2.17 on 2026-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantlog',
            name='status',
            field=models.CharField(choices=[('answered', 'Answered from reviewed records'), ('no_reviewed_data', 'No reviewed records matched'), ('unverified', 'Answer failed verification (not shown)'), ('too_many_drugs', 'Question names too many drugs'), ('unavailable', 'Assistant not configured'), ('error', 'Model call failed')], max_length=20),
        ),
    ]
