# Generated by Django 5.2.17 on 2026-09-30 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('pharma', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(help_text='ISO 4217', max_length=3)),
                ('price_type', models.CharField(choices=[('manufacturer_suggested', 'Manufacturer suggested price'), ('distributor', 'Distributor price'), ('retail', 'Retail price')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origin', models.CharField(choices=[('official', 'Official/regulatory source'), ('manufacturer', 'Manufacturer supplied'), ('editorial', 'Entered by editors from a cited source'), ('user_submitted', 'User submitted (moderated)')], max_length=16)),
                ('observed_on', models.DateField(help_text='Date the price applied or was checked')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='countries.country')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='pharma.productpack')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.source')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('new_price', 'Updated price'), ('report_incorrect', 'Report incorrect price')], max_length=16)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('price_type', models.CharField(blank=True, choices=[('manufacturer_suggested', 'Manufacturer suggested price'), ('distributor', 'Distributor price'), ('retail', 'Retail price')], max_length=24)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.CharField(blank=True, max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='countries.country')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pharma.productpack')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_submissions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='pricing.pricerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['pack', 'country', 'price_type', '-observed_on'], name='pricing_pri_pack_id_9e2ea2_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='price_confidence_0_1'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.CheckConstraint(condition=models.Q(('origin', 'user_submitted'), ('source__isnull', False), _connector='OR'), name='price_needs_source_unless_user'),
        ),
        migrations.AddIndex(
            model_name='pricesubmission',
            index=models.Index(fields=['status', '-created_at'], name='pricing_pri_status_27cfcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricesubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'new_price'), _negated=True), models.Q(('amount__gt', 0), ('amount__isnull', False), models.Q(('price_type', ''), _negated=True)), _connector='OR'), name='new_price_needs_amount_and_type'),
        ),
        migrations.AddConstraint(
            model_name='pricesubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'report_incorrect'), _negated=True), ('target__isnull', False), _connector='OR'), name='report_needs_target'),
        ),
    ]
