# Generated by Django 5.2.17 on 2026-09-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('regulatory', 'Regulatory authority'), ('product_label', 'Registered product label'), ('manufacturer', 'Manufacturer documentation'), ('paper', 'Peer-reviewed paper'), ('textbook', 'Veterinary textbook'), ('pharmacology_ref', 'Pharmacology reference'), ('government', 'Government publication'), ('university', 'University source'), ('organization', 'Recognized veterinary organization'), ('other', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('accessed_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('license_note', models.CharField(blank=True, max_length=300)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='countries.country')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('locator', models.CharField(blank=True, help_text='Page, section or table', max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='sources.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('url', ''), _negated=True), models.Q(('doi', ''), _negated=True), models.Q(('publisher', ''), _negated=True), _connector='OR'), name='source_has_locator'),
        ),
        migrations.AddIndex(
            model_name='sourcelink',
            index=models.Index(fields=['content_type', 'object_id'], name='sources_sou_content_cdcba6_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcelink',
            constraint=models.UniqueConstraint(fields=('source', 'content_type', 'object_id', 'locator'), name='uniq_source_link'),
        ),
    ]
