# Generated by Django 5.2.17 on 2026-09-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('failed', 'Failed')], default='running', max_length=8)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('kind', models.CharField(choices=[('jobs', 'Jobs'), ('scholarships', 'Scholarships')], max_length=14)),
                ('organization', models.CharField(help_text='Shown as the employer/provider of every item from this feed', max_length=200)),
                ('default_job_type', models.CharField(blank=True, help_text='Required for jobs', max_length=12)),
                ('default_level', models.CharField(blank=True, help_text='Required for scholarships', max_length=12)),
                ('license_note', models.CharField(blank=True, help_text='Terms allowing reuse of the feed (required to enable)', max_length=300)),
                ('robots_confirmed_at', models.DateTimeField(blank=True, editable=False, help_text='Set only by a successful robots.txt check', null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('last_checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_result', models.CharField(blank=True, editable=False, max_length=300)),
                ('default_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='countries.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField()),
                ('ok', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='sources.source')),
            ],
            options={
                'verbose_name_plural': 'source health',
            },
        ),
    ]
