# Generated by Django 5.2.17 on 2026-09-30 08:04

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('countries', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(editable=False, max_length=200, unique=True)),
                ('cas_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pharma.drugclass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(editable=False, max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mechanism', models.TextField(blank=True)),
                ('drug_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generics', to='pharma.drugclass')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='generics', to='pharma.ingredient')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=200)),
                ('normalized_synonym', models.CharField(editable=False, max_length=200, unique=True)),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='pharma.generic')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGeneric',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True)),
                ('mechanism', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('drug_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharma.drugclass')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical generic',
                'verbose_name_plural': 'historical generics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('brand_name', models.CharField(max_length=200)),
                ('normalized_brand_name', models.CharField(editable=False, max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_biologic', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('generic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharma.generic')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('marketing_holder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('brand_name', models.CharField(max_length=200)),
                ('normalized_brand_name', models.CharField(editable=False, max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_biologic', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pharma.generic')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufactured_products', to='companies.company')),
                ('marketing_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketed_products', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductRegistration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('registration_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='countries.country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharma.product')),
            ],
            options={
                'verbose_name': 'historical product registration',
                'verbose_name_plural': 'historical product registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_value', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('per_value', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharma.ingredient')),
                ('per_unit', models.ForeignKey(blank=True, help_text='mL, g, tablet... Empty when the strength is stated per unit dose.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='units.unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='pharma.product')),
                ('strength_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_size_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('barcode', models.CharField(blank=True, max_length=32)),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharma.dosageform')),
                ('pack_size_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='units.unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='pharma.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('registration_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='countries.country')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='pharma.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='drugclass',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_class_name'),
        ),
        migrations.AddConstraint(
            model_name='generic',
            constraint=models.CheckConstraint(condition=models.Q(('is_development_data', True), ('review_status__in', ['expert_reviewed', 'verified']), _negated=True), name='pharma_generic_no_signoff_on_dev_data'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('is_development_data', True), ('review_status__in', ['expert_reviewed', 'verified']), _negated=True), name='pharma_product_no_signoff_on_dev_data'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'normalized_brand_name'), name='uniq_product_brand'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='uniq_product_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.CheckConstraint(condition=models.Q(('strength_value__gt', 0)), name='strength_positive'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.CheckConstraint(condition=models.Q(('per_value__gt', 0)), name='per_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='productpack',
            constraint=models.UniqueConstraint(fields=('product', 'dosage_form', 'pack_size_value', 'pack_size_unit'), name='uniq_product_pack'),
        ),
        migrations.AddConstraint(
            model_name='productpack',
            constraint=models.CheckConstraint(condition=models.Q(('pack_size_value__gt', 0)), name='pack_positive'),
        ),
        migrations.AddConstraint(
            model_name='productregistration',
            constraint=models.CheckConstraint(condition=models.Q(('is_development_data', True), ('review_status__in', ['expert_reviewed', 'verified']), _negated=True), name='pharma_productregistration_no_signoff_on_dev_data'),
        ),
        migrations.AddConstraint(
            model_name='productregistration',
            constraint=models.UniqueConstraint(fields=('country', 'registration_number'), name='uniq_registration_number'),
        ),
    ]
