# Generated by Django 5.2.17 on 2026-09-30 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('countries', '0001_initial'),
        ('pharma', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='products', max_length=24)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('checksum', models.CharField(help_text='SHA-256 of the raw file', max_length=64)),
                ('status', models.CharField(choices=[('staged', 'Staged (awaiting review)'), ('completed', 'Completed')], default='staged', max_length=12)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='countries.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw', models.JSONField()),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registration_status', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved into catalogue (unreviewed)'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate of an existing record'), ('error', 'Invalid row')], default='pending', max_length=12)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.importbatch')),
                ('matched_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company')),
                ('matched_generic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pharma.generic')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pharma.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('kind', 'country', 'checksum'), name='uniq_import_file_per_country'),
        ),
        migrations.AddConstraint(
            model_name='stagedrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_batch_row'),
        ),
    ]
