# Generated by Django 5.2.17 on 2026-09-30 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('dimension', models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('concentration', 'Concentration'), ('dose_rate', 'Dose Rate'), ('body_weight', 'Body Weight'), ('time', 'Time'), ('percent', 'Percent'), ('activity', 'Activity'), ('count', 'Count')], max_length=16)),
                ('to_base', models.DecimalField(decimal_places=15, default=Decimal('1'), help_text="Multiply a value in this unit by this to get the dimension's base unit.", max_digits=30)),
            ],
            options={
                'ordering': ['dimension', 'code'],
            },
        ),
    ]
