# Generated by Django 5.2.17 on 2026-09-30 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('edition', models.CharField(blank=True, max_length=60)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True, help_text='Publisher or library page, not a pirated copy')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('front', models.CharField(max_length=500)),
                ('back', models.TextField()),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flashcards', to='education.topic')),
            ],
            options={
                'ordering': ['topic__subject__name', 'topic__name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_on', models.DateField()),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('times_wrong', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='education.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('body', models.TextField(help_text='Plain text; blank lines separate paragraphs.')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='education.topic')),
            ],
            options={
                'ordering': ['topic__subject__name', 'topic__name', 'title'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.CheckConstraint(condition=models.Q(('is_development_data', True), ('review_status__in', ['expert_reviewed', 'verified']), _negated=True), name='education_flashcard_no_signoff_on_dev_data'),
        ),
        migrations.AddConstraint(
            model_name='flashcardprogress',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='uniq_progress_per_card'),
        ),
        migrations.AddConstraint(
            model_name='flashcardprogress',
            constraint=models.CheckConstraint(condition=models.Q(('box__gte', 1), ('box__lte', 5)), name='flashcard_box_1_5'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('is_development_data', True), ('review_status__in', ['expert_reviewed', 'verified']), _negated=True), name='education_lesson_no_signoff_on_dev_data'),
        ),
    ]
