# Generated by Django 5.2.17 on 2026-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_bookreference_flashcard_flashcardprogress_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='review_status',
            field=models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('imported_unverified', 'Imported, not reviewed'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='review_status',
            field=models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('imported_unverified', 'Imported, not reviewed'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='review_status',
            field=models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('imported_unverified', 'Imported, not reviewed'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32),
        ),
    ]
