# Generated by Django 5.2.17 on 2026-09-30 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('needs_verification', 'Needs verification'), ('source_found_pending_review', 'Source found, pending review'), ('manufacturer_supplied', 'Manufacturer supplied'), ('official_regulatory', 'Official regulatory source'), ('expert_reviewed', 'Expert reviewed'), ('verified', 'Verified'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='needs_verification', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_development_data', models.BooleanField(default=False, help_text='Seed/test record. Never shown as verified.')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(editable=False, max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('is_manufacturer', models.BooleanField(default=False)),
                ('is_importer', models.BooleanField(default=False)),
                ('is_distributor', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_verified_profile', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='countries.country')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('normalized_alias', models.CharField(editable=False, max_length=200, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='companies.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('is_development_data', True), ('review_status__in', ['expert_reviewed', 'verified']), _negated=True), name='companies_company_no_signoff_on_dev_data'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('country', 'normalized_name'), name='uniq_company_country_name'),
        ),
    ]
